name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:ubuntu-latest

    steps:
      -name: display
        run: echo "deploying to the main branch"
        run: echo "deploying basic code"