name: deploy

on:
  push:
    branches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          echo "deploying to the staging"
          echo "deploying to the production"
